"""Markdown report rendering for the statistical summary.

The report intentionally uses a small, common set of statistics:
mean, 95% percentile bootstrap CI, exact two-sided sign-test p-value,
and Clopper-Pearson exact CI for SHACL pass-rate. No Cliff's delta or
other rank effect sizes — the paired mean delta and its CI carry the
same information at the cell sizes we run here, and reviewers do not
have to learn an extra metric.
"""

from __future__ import annotations

import math


def _fmt_ci(lo: float, hi: float, digits: int = 3) -> str:
    if math.isnan(lo) or math.isnan(hi):
        return "—"
    return f"[{lo:.{digits}f}, {hi:.{digits}f}]"


def _fmt_pc(val: float | None, ci: list) -> str:
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return "—"
    lo, hi = ci
    ci_str = _fmt_ci(lo, hi, digits=2)
    return f"{val:.3f} {ci_str}"


def _fmt_p(p: float) -> str:
    """Sign-test p-value formatting. Tiny p values get "<0.001"."""
    if p < 0.001:
        return "<0.001"
    return f"{p:.3f}"


def _render_markdown(cells: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Statistical summary")
    lines.append("")
    lines.append("Honest-effort statistical reporting over the (track × prompt)")
    lines.append("ablation cells from the main evaluation runs.")
    lines.append("")
    cell_ns = sorted({c["n"] for c in cells})
    cell_n_str = "/".join(str(x) for x in cell_ns) if cell_ns else "?"
    lines.append(f"**Sample sizes (n = {cell_n_str} vignettes per cell).**")
    lines.append("")
    lines.append("**Reporting model.** All bootstrap CIs are 95% percentile")
    lines.append("intervals over 10 000 resamples (seed fixed for reproducibility).")
    lines.append("SHACL pass-rate CIs are exact Clopper–Pearson. Paired F1")
    lines.append("comparisons report the mean within-vignette delta, its CI,")
    lines.append("and an exact two-sided sign-test p-value. We do **not**")
    lines.append("report Cliff's delta — at these cell sizes the paired")
    lines.append("mean delta and its CI carry the same directional information")
    lines.append("without an extra metric.")
    lines.append("")
    lines.append("**F1 validity.** Triple-level F1 (precision/recall) is computed")
    lines.append("in a canonical-IRI space established by `pipeline/iri_normalizer.py`:")
    lines.append("Synthea-derived gold ABoxes use UUID-derived IRIs that the LLM cannot")
    lines.append("reproduce verbatim, so the normaliser aligns LLM output IRIs to gold")
    lines.append("IRIs via FHIR-grounded matching keys (rdfs:label, literal values, IRI")
    lines.append("token overlap, structural anchoring). Without it, F1 would be ~0 by")
    lines.append("construction; with it, every vignette contributes to the F1 mean.")
    lines.append("")
    lines.append("**Output-presence filter.** Means for OC, PC, and SHACL pass-rate")
    lines.append("are over vignettes where the system actually produced output")
    lines.append("(``output_present=true``). Vignettes a system was never run on are")
    lines.append("excluded — their absence is a missing-data problem, not a SHACL or")
    lines.append("PC failure. Each system row prints its own present-count.")
    lines.append("")
    lines.append("**PC interpretation.** Property Completeness measures, for each")
    lines.append("typed instance the LLM produces, what fraction of its")
    lines.append("SHACL-declared property slots are populated. PC = 1.0 means every")
    lines.append("extracted entity has all its expected attributes; PC = 0.0 means")
    lines.append("entities were typed but every property is missing. A graph with no")
    lines.append("typed instances reports PC = NaN. PC complements SHACL conformance:")
    lines.append("an empty graph passes SHACL trivially but scores no PC.")
    lines.append("")
    lines.append("Generated by `pipeline/stats.py`. Raw output: `evaluation/outputs/stats.json`.")
    lines.append("")

    # --- Per-cell table ---
    lines.append("## Per-cell descriptives (F1 vs gold + SHACL + PC)")
    lines.append("")
    lines.append(
        "| Track | Prompt | Sys | n | n_pres | F1 n | F1 mean | F1 boot95 CI | "
        "OC mean | SHACL pass | SHACL CP95 | PC mean (boot95 CI) |"
    )
    lines.append(
        "| --- | --- | :-: | :-: | :-: | :-: | ---: | :-: | ---: | :-: | :-: | :-- |"
    )
    for cell in cells:
        for sys_ in ("a", "b", "c"):
            s = cell["systems"][sys_]
            pc_str = _fmt_pc(s.get("pc_mean"), s.get("pc_boot95", [float("nan"), float("nan")]))
            present = s.get("present_count", cell["n"])
            lines.append(
                f"| {cell['track']:<8} | {cell['prompt']:<8} | {sys_.upper()} | "
                f"{cell['n']} | {present} | "
                f"{s.get('f1_comparable_count', cell.get('f1_n', cell['n']))} | "
                f"{s['f1_mean']:.3f} | "
                f"{_fmt_ci(*s['f1_boot95'])} | "
                f"{s['oc_mean']:.3f} | {s['shacl_pass_count']}/{present} | "
                f"{_fmt_ci(*s['shacl_pass_cp95'], digits=2)} | {pc_str} |"
            )
    lines.append("")

    # --- Paired comparisons ---
    lines.append("## Paired F1 comparisons (within-vignette deltas)")
    lines.append("")
    lines.append("Mean within-vignette F1 delta (positive ⇒ first system beats")
    lines.append("second), 95% percentile bootstrap CI on the mean delta, and")
    lines.append("the two-sided exact sign-test p-value. ``+/-/=`` are the counts")
    lines.append("of vignettes where the first system was higher / lower / tied.")
    lines.append("")
    lines.append("| Track | Prompt | Contrast | n pairs | Mean Δ F1 | CI95 | sign p | +/−/= |")
    lines.append("| --- | --- | --- | :-: | ---: | :-: | ---: | :-: |")
    for cell in cells:
        for key, rec in cell["paired"].items():
            if rec is None:
                continue
            lines.append(
                f"| {cell['track']:<8} | {cell['prompt']:<8} | {key.upper():<4} | "
                f"{len(rec['deltas'])} | "
                f"{rec['mean_delta']:+.4f} | {_fmt_ci(*rec['ci95'], digits=4)} | "
                f"{_fmt_p(rec['sign_p'])} | "
                f"{rec.get('n_pos', '?')}/{rec.get('n_neg', '?')}/{rec.get('n_tie', '?')} |"
            )
    lines.append("")

    # --- Notes ---
    lines.append("## Notes on interpretation")
    lines.append("")
    lines.append("1. **Bootstrap CIs are percentile intervals.** The bound")
    lines.append("   cannot fall outside the observed min/max without more data.")
    lines.append("   A tight CI means the per-vignette scores agree, not that")
    lines.append("   the estimate is precise in a population sense.")
    lines.append("")
    lines.append("2. **Sign-test p-values are exact** (binomial against p=0.5)")
    lines.append("   over within-vignette F1 differences, with ties dropped.")
    lines.append("   Intermediate p-values mean the test cannot reject — not")
    lines.append("   that the systems are equivalent.")
    lines.append("")
    lines.append("3. **Clopper–Pearson on SHACL pass-rate** is the right CI")
    lines.append("   for a binomial proportion. Pairs of intervals may overlap")
    lines.append("   even when the underlying point estimates differ — those")
    lines.append("   overlaps are directional evidence, not equivalence.")
    lines.append("")
    lines.append("4. **Why no Cliff's delta.** The paired mean Δ F1 plus its")
    lines.append("   bootstrap CI already discriminates direction; Cliff's δ")
    lines.append("   adds a metric reviewers must learn without changing the")
    lines.append("   conclusion at this sample size.")
    lines.append("")
    return "\n".join(lines)
