"""FHIR Bundle → CHR Turtle ABox converter (encounter-centric).

Reads a Synthea-generated FHIR R4 Bundle and emits, for every "rich"
Encounter (one that has at least one attached Observation and Condition),
a CHR-aligned Turtle ABox compatible with the schema-track gold format
in evaluation/corpus/abox_gold/vignette_NN_gold_schema.ttl.

Each rich Encounter becomes one vignette, so a single Synthea bundle
typically yields 5-15 vignettes. Generating ~15 patients gives n=100+.

Usage::

    python scaling_n100/fhir_to_chr.py --bundle <bundle.json> --vid_prefix vignette \\
        --start_index 1 --out_dir evaluation/corpus/abox_gold/

Each rich encounter produces:
    <out_dir>/vignette_NNN_gold_schema.ttl

The matching synthetic vignette text is generated by fhir_to_text.py.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import RDF, RDFS, XSD

CHR = Namespace("https://w3id.org/shexmap/resource/ontology-schema/d285f599-dc2e-4bd0-83f3-df21defa8821/")
SULO = Namespace("https://w3id.org/sulo/")
EX  = Namespace("http://example.org/clinical/")


def _slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_")


def _ex_iri(prefix: str, ident: str) -> URIRef:
    return EX[f"{prefix}_{_slug(ident)}"]


def _ref_id(ref: str) -> str:
    """Strip 'urn:uuid:' or 'ResourceType/' prefix to get bare ID."""
    if ref.startswith("urn:uuid:"):
        return ref[len("urn:uuid:"):]
    if "/" in ref:
        return ref.split("/", 1)[1]
    if "?" in ref:
        return ref.split("?", 1)[1]  # Practitioner?identifier=...
    return ref


def _build_resource_index(bundle: dict) -> dict[str, dict]:
    """Map ID → resource. Uses both bare and urn:uuid keys."""
    idx: dict[str, dict] = {}
    for entry in bundle.get("entry", []):
        r = entry.get("resource", {})
        rid = r.get("id", "")
        if rid:
            idx[rid] = r
            idx[f"urn:uuid:{rid}"] = r
            idx[f"{r.get('resourceType')}/{rid}"] = r
    return idx


def _attached_to_encounter(bundle: dict, encounter_id: str) -> dict[str, list]:
    """Return {ResourceType: [resources]} attached to this encounter."""
    out: dict[str, list] = {}
    enc_refs = {f"urn:uuid:{encounter_id}", f"Encounter/{encounter_id}", encounter_id}
    for entry in bundle.get("entry", []):
        r = entry.get("resource", {})
        ref_str = ""
        if "encounter" in r and isinstance(r["encounter"], dict):
            ref_str = r["encounter"].get("reference", "")
        elif "context" in r and isinstance(r["context"], dict):
            ref_str = r["context"].get("reference", "")
        if ref_str in enc_refs:
            out.setdefault(r["resourceType"], []).append(r)
    return out


def _label(res: dict, fallback: str) -> str:
    """Best-effort human label for a FHIR resource."""
    name_list = res.get("name")
    if isinstance(name_list, list) and name_list:
        n = name_list[0]
        given = " ".join(n.get("given", []))
        family = n.get("family", "")
        full = f"{given} {family}".strip()
        if full:
            prefix = " ".join(n.get("prefix", []))
            return f"{prefix} {full}".strip()
    if isinstance(name_list, str):
        return name_list
    if "display" in res:
        return res["display"]
    text = res.get("code", {}).get("text") if isinstance(res.get("code"), dict) else None
    if text:
        return text
    return fallback


def convert_encounter(
    bundle: dict,
    encounter: dict,
    res_idx: dict[str, dict],
    vid: str,
) -> Graph:
    """Convert one Encounter (and its attached resources) into a CHR ABox."""
    g = Graph()
    g.bind("chr", CHR)
    g.bind("sulo", SULO)
    g.bind("ex", EX)
    g.bind("rdfs", RDFS)
    g.bind("xsd", XSD)

    eid = encounter["id"]
    attached = _attached_to_encounter(bundle, eid)

    # ---- Patient ----
    pat_ref = encounter.get("subject", {}).get("reference", "")
    patient_iri = _ex_iri("patient", _ref_id(pat_ref))
    pat_res = res_idx.get(_ref_id(pat_ref))
    g.add((patient_iri, RDF.type, CHR.Person))
    if pat_res:
        g.add((patient_iri, RDFS.label, Literal(_label(pat_res, "Patient"))))

    # ---- Provider (primary performer) ----
    provider_iri = None
    for participant in encounter.get("participant", []):
        ind = participant.get("individual", {}).get("reference", "")
        if ind:
            prov_id = _ref_id(ind)
            provider_iri = _ex_iri("provider", prov_id.replace("identifier=", "")[:30])
            prov_res = res_idx.get(prov_id)
            g.add((provider_iri, RDF.type, CHR.Person))
            if prov_res:
                g.add((provider_iri, RDFS.label, Literal(_label(prov_res, "Practitioner"))))
            else:
                # external practitioner reference — extract name from display
                disp = participant.get("individual", {}).get("display", "Practitioner")
                g.add((provider_iri, RDFS.label, Literal(disp)))
            break

    # ---- Care unit (serviceProvider) ----
    care_unit_iri = None
    sp_ref = encounter.get("serviceProvider", {}).get("reference", "")
    if sp_ref:
        sp_id = _ref_id(sp_ref)
        care_unit_iri = _ex_iri("unit", sp_id[:20])
        sp_res = res_idx.get(sp_id)
        g.add((care_unit_iri, RDF.type, CHR.CareUnit))
        if sp_res:
            g.add((care_unit_iri, RDFS.label, Literal(sp_res.get("name", "Care Unit"))))
        else:
            disp = encounter.get("serviceProvider", {}).get("display", "Care Unit")
            g.add((care_unit_iri, RDFS.label, Literal(disp)))

    # ---- Visit ----
    visit_iri = _ex_iri("visit", eid)
    g.add((visit_iri, RDF.type, CHR.ClinicalVisit))
    g.add((visit_iri, CHR.hasPatient, patient_iri))
    if provider_iri:
        g.add((visit_iri, CHR.hasCareProvider, provider_iri))
    if care_unit_iri:
        g.add((visit_iri, CHR.hasCareUnit, care_unit_iri))

    # NOTE: chr:hasRecordDate is restricted to ClinicalCondition subjects
    # (HasRecordDateShape). Don't attach to Visit. Per-process timestamps
    # use chr:hasPerformedDate / chr:hasMeasuredDate instead.
    period_start = encounter.get("period", {}).get("start")

    # ---- Status (shared across measurement/eval procs) ----
    status_iri = _ex_iri("status", "completed")
    g.add((status_iri, RDF.type, CHR.ProcessStatus))
    g.add((status_iri, RDFS.label, Literal("completed")))

    # ---- Observations → MeasurementProcess + Measurement + Quantity ----
    for i, obs in enumerate(attached.get("Observation", [])):
        oid = obs.get("id", f"obs{i}")
        # only quantitative observations
        vq = obs.get("valueQuantity")
        if not vq or "value" not in vq:
            continue
        meas_iri = _ex_iri("meas", oid)
        g.add((meas_iri, RDF.type, CHR.Measurement))
        g.add((meas_iri, CHR.hasQuantityValue, Literal(float(vq["value"]), datatype=XSD.float)))
        unit = vq.get("unit") or vq.get("code", "unit")
        # chr:hasUnit must be an IRI (HasUnitRangeShape, sh:nodeKind sh:IRI).
        # Mint a sulo:Unit IRI for the unit symbol — matches the gold-vignette
        # convention `chr:hasUnit <https://w3id.org/sulo/Unit/mmHg>`.
        unit_iri = URIRef(f"https://w3id.org/sulo/Unit/{_slug(unit)}")
        g.add((meas_iri, CHR.hasUnit, unit_iri))
        if "effectiveDateTime" in obs:
            g.add((meas_iri, CHR.hasMeasuredDate, Literal(obs["effectiveDateTime"], datatype=XSD.dateTime)))

        proc_iri = _ex_iri("measProc", oid)
        g.add((proc_iri, RDF.type, CHR.MeasurementProcess))
        g.add((proc_iri, CHR.hasPatient, patient_iri))
        if provider_iri:
            g.add((proc_iri, CHR.hasPerformer, provider_iri))
        g.add((proc_iri, CHR.hasResult, meas_iri))
        g.add((proc_iri, CHR.hasStatus, status_iri))
        if "effectiveDateTime" in obs:
            g.add((proc_iri, CHR.hasPerformedDate, Literal(obs["effectiveDateTime"], datatype=XSD.dateTime)))

    # ---- Conditions → ClinicalCondition + DiagnosticStatement + EvaluationProcess ----
    for i, cond in enumerate(attached.get("Condition", [])):
        cid = cond.get("id", f"cond{i}")
        code = cond.get("code", {})
        label = code.get("text") or (code.get("coding", [{}])[0].get("display", "Condition"))

        cond_iri = _ex_iri("cond", cid)
        g.add((cond_iri, RDF.type, CHR.ClinicalCondition))
        g.add((cond_iri, RDFS.label, Literal(label)))
        if "recordedDate" in cond:
            g.add((cond_iri, CHR.hasRecordDate, Literal(cond["recordedDate"], datatype=XSD.dateTime)))

        diag_iri = _ex_iri("diag", cid)
        g.add((diag_iri, RDF.type, CHR.DiagnosticStatement))
        g.add((diag_iri, RDFS.label, Literal(label)))

        eval_iri = _ex_iri("evalProc", cid)
        g.add((eval_iri, RDF.type, CHR.EvaluationProcess))
        g.add((eval_iri, CHR.hasPatient, patient_iri))
        if provider_iri:
            g.add((eval_iri, CHR.hasPerformer, provider_iri))
        g.add((eval_iri, CHR.hasObservation, diag_iri))
        if period_start:
            g.add((eval_iri, CHR.hasPerformedDate, Literal(period_start, datatype=XSD.dateTime)))

    # ---- MedicationAdministrations → MedAdmin + PharmaceuticalProduct ----
    for i, ma in enumerate(attached.get("MedicationAdministration", [])):
        mid = ma.get("id", f"ma{i}")
        med = ma.get("medicationCodeableConcept", {}) or {}
        med_text = med.get("text") or (med.get("coding", [{}])[0].get("display", "Medication"))

        prod_iri = _ex_iri("drug", mid)
        g.add((prod_iri, RDF.type, CHR.PharmaceuticalProduct))
        g.add((prod_iri, RDFS.label, Literal(med_text)))

        admin_iri = _ex_iri("medAdmin", mid)
        g.add((admin_iri, RDF.type, CHR.MedicationAdministration))
        g.add((admin_iri, CHR.hasPatient, patient_iri))
        if provider_iri:
            g.add((admin_iri, CHR.hasPerformer, provider_iri))
        g.add((admin_iri, CHR.hasPharmaceuticalProduct, prod_iri))
        if "effectiveDateTime" in ma:
            g.add((admin_iri, CHR.hasPerformedDate, Literal(ma["effectiveDateTime"], datatype=XSD.dateTime)))

    return g


def is_rich(bundle: dict, encounter: dict) -> bool:
    """Encounter must have ≥1 Observation with valueQuantity AND ≥1 Condition."""
    att = _attached_to_encounter(bundle, encounter["id"])
    has_obs = any(o.get("valueQuantity") for o in att.get("Observation", []))
    has_cond = bool(att.get("Condition"))
    return has_obs and has_cond


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bundle", required=True, type=Path)
    ap.add_argument("--vid_prefix", required=True, help="e.g. 'synthea' → synthea_001, ...")
    ap.add_argument("--start_index", type=int, default=1)
    ap.add_argument("--out_dir", required=True, type=Path)
    args = ap.parse_args()

    bundle = json.loads(args.bundle.read_text())
    res_idx = _build_resource_index(bundle)
    encounters = [e["resource"] for e in bundle.get("entry", []) if e["resource"].get("resourceType") == "Encounter"]
    rich = [e for e in encounters if is_rich(bundle, e)]
    args.out_dir.mkdir(parents=True, exist_ok=True)

    print(f"[INFO] {len(encounters)} encounters, {len(rich)} rich")
    for i, enc in enumerate(rich):
        vid = f"{args.vid_prefix}_{args.start_index + i:03d}"
        g = convert_encounter(bundle, enc, res_idx, vid)
        out = args.out_dir / f"{vid}_gold_schema.ttl"
        g.serialize(out.as_posix(), format="turtle")
    print(f"[OK] Wrote {len(rich)} ABox files to {args.out_dir}")
    return len(rich)


if __name__ == "__main__":
    main()
